### ISSUE TITLE
图片出处

### ISSUE THREAD

**Issue by linrl3** [tonydeng/sdn-handbook#13]
你好，请问https://tonydeng.github.io/sdn-handbook/linux/tc.html 中英文的结构图出自哪些资料？我想查阅相关资料，谢谢。

**Comment by tonydeng** [comment]
@linrl3 具体哪个图？

**Comment by linrl3** [comment]
@tonydeng htb示例下的第一个图

**Comment by tonydeng** [comment]
在[流量控制](https://tonydeng.github.io/sdn-handbook/linux/tc.html)这一节的参考文档部分

http://linux-ip.net/articles/Traffic-Control-HOWTO/diagram.html#d-general
